
USE DB;

SELECT 
COLUMN_NAME, 
DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = Zomato																				-- Check Datatype of table


SELECT DISTINCT(TABLE_CATALOG),TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS										-- CHECK TABLES IN ALL THE DATABSE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

SELECT * FROM Zomato


--CHECKING FOR DUPLICATE
SELECT RestaurantID,COUNT(RestaurantID) FROM Zomato
GROUP BY RestaurantID
ORDER BY 2 DESC

SELECT * FROM ZOMATO_COUNTRY;



--REMOVING UNWANTED ROWS
DELETE FROM Zomato 
WHERE CountryCode IN (' Bar',' Grill',' Bakers & More"',' Chowringhee Lane"',' Grill & Bar"',' Chinese')

DELETE FROM Zomato 
WHERE RestaurantID = '18306543'

SELECT * FROM Zomato


-- COUNTRY CODE COLUMN
SELECT A.CountryCode,B.COUNTRY
FROM Zomato A JOIN ZOMATO_COUNTRY B
ON A.CountryCode = B.COUNTRYCODE

ALTER TABLE Zomato ADD COUNTRY_NAME VARCHAR(50)

UPDATE Zomato SET COUNTRY_NAME = B.COUNTRY								 -- MERGING AND ADDING COUNTRY DETAILS FROM DIFFERENT TABLE THROUGH UPDATE WITH JOIN STATEMENT
FROM Zomato A JOIN ZOMATO_COUNTRY B
ON A.CountryCode = B.COUNTRYCODE

SELECT *
FROM Zomato



--CITY COLUMN
SELECT DISTINCT City FROM Zomato 
WHERE CITY LIKE '%?%'																  --IDENTIFYING IF THERE ARE ANY MISS-SPELLED WORD

SELECT REPLACE(CITY,'?','i') 
FROM Zomato WHERE CITY LIKE '%?%'											  --REPLACING MISS-SPELLED WORD

UPDATE Zomato SET City  = REPLACE(CITY,'?','i') 
					 FROM ZomatoData1 WHERE CITY LIKE '%?%'	 			 -- UPDATING WITH REPLACE STRING FUNCTION

SELECT COUNTRY_NAME, CITY, COUNT(City) TOTAL_REST							      -- COUNTING TOTAL REST. IN EACH CITY OF PARTICULAR COUNTRY
FROM Zomato
GROUP BY COUNTRY_NAME,CITY 
ORDER BY 1,2,3 DESC



--LOCALITY COLUMN
SELECT CITY,Locality, COUNT(Locality) COUNT_LOCALITY,														-- ROLLING COUNT
SUM(COUNT(Locality)) OVER(PARTITION BY City ORDER BY CITY,Locality) ROLL_COUNT
FROM Zomato
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY Locality,CITY
ORDER BY 1,2,3 DESC



--DROP COLUMN,[Locality],[LocalityVerbose][Address]
ALTER TABLE Zomato DROP COLUMN Address
ALTER TABLE Zomato DROP COLUMN LocalityVerbose 



-- CUISINES COLUMN 
SELECT Cuisines, COUNT(Cuisines) FROM Zomato
WHERE Cuisines IS NULL OR Cuisines = ' '
GROUP BY Cuisines
ORDER BY 2 DESC

SELECT Cuisines,COUNT(Cuisines)
FROM Zomato
GROUP BY Cuisines
ORDER BY 2 DESC


-- CURRENCY COULMN
SELECT Currency, COUNT(Currency) FROM Zomato
GROUP BY Currency
ORDER BY 2 DESC



-- YES/NO COLUMNS
SELECT DISTINCT(Has_Table_booking) FROM ZomatoData1
SELECT DISTINCT(Has_Online_delivery) FROM ZomatoData1
SELECT DISTINCT(Is_delivering_now) FROM ZomatoData1
SELECT DISTINCT(Switch_to_order_menu) FROM Zomato



-- DROP COULLMN [Switch_to_order_menu]
ALTER TABLE Zomato DROP COLUMN Switch_to_order_menu



-- PRICE RANGE COLUMN
SELECT DISTINCT(Price_range) FROM Zomato



-- VOTES COLUMN (CHECKING MIN,MAX,AVG OF VOTE COLUMN)
ALTER TABLE Zomato ALTER COLUMN Votes INT

SELECT MIN(CAST(Votes AS INT)) MIN_VT,AVG(CAST(Votes AS INT)) AVG_VT,MAX(CAST(Votes AS INT)) MAX_VT
FROM Zomato



-- COST COLUMN
ALTER TABLE Zomato ALTER COLUMN Average_Cost_for_two FLOAT

SELECT Currency,MIN(CAST(Average_Cost_for_two AS INT)) MIN_CST,
AVG(CAST(Average_Cost_for_two AS INT)) AVG_CST,
MAX(CAST(Average_Cost_for_two AS INT)) MAX_CST
FROM Zomato
--WHERE [Currency] LIKE '%U%'
GROUP BY Currency



--RATING COLUMN
SELECT MIN(Rating),
ROUND(AVG(CAST(Rating AS DECIMAL)),1), 
MAX(Rating)  
FROM Zomato

SELECT CAST(Rating AS decimal) NUM FROM Zomato WHERE CAST(Rating AS decimal) >= 4

ALTER TABLE Zomato ALTER COLUMN Rating DECIMAL

SELECT RATING FROM Zomato WHERE Rating >= 4

SELECT RATING,CASE
WHEN Rating >= 1 AND Rating < 2.5 THEN 'POOR'
WHEN Rating] >= 2.5 AND Rating < 3.5 THEN 'GOOD'
WHEN Rating >= 3.5 AND Rating < 4.5 THEN 'GREAT'
WHEN Rating >= 4.5 THEN 'EXCELLENT'
END RATE_CATEGORY
FROM Zomato

ALTER TABLE Zomato ADD RATE_CATEGORY VARCHAR(20)

SELECT * FROM Zomato



--UPDATING NEW ADDED COLUMN WITH REFFERENCE OF AN EXISTING COLUMN
UPDATE Zomato SET RATE_CATEGORY = (CASE								     	-- UPDATE WITH CASE-WHEN STATEMENT
WHEN Rating >= 1 AND Rating < 2.5 THEN 'POOR'
WHEN Rating >= 2.5 AND Rating < 3.5 THEN 'GOOD'
WHEN Rating >= 3.5 AND Rating < 4.5 THEN 'GREAT'
WHEN Rating >= 4.5 THEN 'EXCELLENT'
END)
