-- ANALYSIS QUESTIONS
USE NEW;


SELECT * FROM ZOMATO;


-- ROLLING/MOVING COUNT OF RESTAURANTS IN INDIAN CITIES
SELECT COUNTRY_NAME, City, Locality, COUNT(Locality) AS TOTAL_REST,
SUM(COUNT(Locality)) OVER(PARTITION BY City ORDER BY Locality DESC) AS ROLL_CNT
FROM ZOMATO
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY  COUNTRY_NAME,City,Locality;


-- WHAT PERCENTAGE OF TOTAL RESTAURANTS LISTED IN ZOMATO IN EACH COUNTRIES
CREATE OR REPLACE VIEW TOTAL_COUNT
AS
(
SELECT COUNT(Distinct RestaurantID) AS TOTAL_REST
FROM ZOMATO
);
SELECT * FROM TOTAL_COUNT;

-- FINAL QUERY AFTER CREATING VIEW
WITH CT1 AS
(
SELECT COUNTRY_NAME, COUNT(RestaurantID) AS REST_COUNT
FROM ZOMATO
GROUP BY COUNTRY_NAME
)
SELECT A.COUNTRY_NAME,A.REST_COUNT ,ROUND((A.REST_COUNT/B.TOTAL_REST)*100,2) AS PERCENTAGE
FROM CT1 A, TOTAL_COUNT B
ORDER BY 3 DESC;


-- COUNTRIES WITH COUNT AND PERCENTAGE OF RESTAURANTS THAT PROVIDES ONLINE DELIVERY OPTION
CREATE OR REPLACE VIEW COUNTRY_REST
AS(
SELECT COUNTRY_NAME, COUNT(RestaurantID) AS REST_COUNT
FROM ZOMATO
GROUP BY COUNTRY_NAME
);
SELECT * FROM COUNTRY_REST
ORDER BY 2 DESC;

SELECT A.COUNTRY_NAME,COUNT(A.RestaurantID) AS TOTAL_REST, 
ROUND((COUNT(A.RestaurantID)/(B.REST_COUNT))*100, 2) AS Percentage
FROM ZOMATO A JOIN COUNTRY_REST B
ON A.COUNTRY_NAME = B.COUNTRY_NAME
WHERE A.Has_Online_delivery = 'YES'
GROUP BY A.COUNTRY_NAME
ORDER BY 2 DESC;


-- WHICH LOCALITY HAS THE MAXIMUM NUMBER OF RESTUARANTS IN EACH CITY OF INDIA
WITH CT1
AS
(
SELECT City,Locality,COUNT(RestaurantID) AS REST_COUNT
FROM ZOMATO
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY CITY,LOCALITY
-- ORDER BY 3 DESC
)
SELECT City, Locality, REST_COUNT FROM CT1 WHERE (City, REST_COUNT) IN (SELECT City, MAX(REST_COUNT) FROM CT1 GROUP BY City);


-- WHICH CITY HAS THE MAXIMUM NUMBER OF RESTUARANTS IN INDIA
WITH CT1
AS
(
SELECT City,COUNT(RestaurantID) AS REST_COUNT
FROM ZOMATO
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY CITY
)
SELECT City, REST_COUNT FROM CT1 WHERE REST_COUNT IN (SELECT MAX(REST_COUNT) FROM CT1);


-- WHICH TYPES OF FOODS ARE AVAILABLE IN LOCALITY WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO FOR INDIA
WITH CT1
AS
(
SELECT City,Locality,COUNT(RestaurantID) AS REST_COUNT
FROM ZOMATO
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY CITY,LOCALITY
),
CT2 AS (
SELECT Locality,REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1)
)
SELECT  B.Cuisines
FROM  CT2 A JOIN ZOMATO B
ON A.Locality = B.Locality;

-- MOST POPULAR CUISINE IN THAT LOCALITY WHERE THE MAXIMUM NUMBER OF RESTUARANTS IS LISTED
-- FOR CREATION OF SEQUENCE
CREATE TABLE numbers (
    n INT
);
DELIMITER //
CREATE PROCEDURE GenerateNumbers()
BEGIN
    DECLARE end INT;
    DECLARE start INT DEFAULT 1;
    SET end = 1 + (SELECT MAX(LENGTH(Cuisines) - LENGTH(REPLACE(Cuisines, '|', ''))) FROM zomato);
    WHILE start <= end DO
        INSERT INTO numbers VALUES (start);
        SET start = start + 1;
    END WHILE;
END //
DELIMITER ;
CALL GenerateNumbers();
-- FOR SPLITTING CUISINES 

WITH CT1
AS
(
	SELECT City,Locality,COUNT(RestaurantID) AS REST_COUNT
	FROM ZOMATO
	WHERE COUNTRY_NAME = 'INDIA'
	GROUP BY CITY,LOCALITY
),
CT2 AS 
(
	SELECT Locality,REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1)
),
CT3 AS 
(
    SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(B.Cuisines, '|', A.n), '|', -1) AS Cuisines 
    FROM ZOMATO B RIGHT JOIN CT2 C ON B.Locality=C.Locality,NUMBERS A
    WHERE 
    A.n <= 1 + (LENGTH(B.Cuisines) - LENGTH(REPLACE(B.Cuisines, ',', '')))
)
SELECT Cuisines,COUNT(Cuisines) AS COUNT FROM CT3 GROUP BY Cuisines ORDER BY 2 DESC;

-- WHICH CITY IN INDIA HAS THE LOWEST RESTAURANTS LISTED IN ZOMATO
WITH CT1 AS
(
SELECT City, COUNT(RestaurantID) AS REST_COUNT
FROM ZOMATO
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY City
)
SELECT * FROM CT1 WHERE REST_COUNT = (SELECT MIN(REST_COUNT) FROM CT1) ORDER BY CITY;



-- HOW MANY RESTAURANTS OFFER TABLE BOOKING OPTION IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO
WITH CT1 AS (
SELECT City,Locality,COUNT(RestaurantID) REST_COUNT
FROM ZOMATO
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY CITY,LOCALITY
),
CT2 AS (
SELECT Locality,REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1)
),
CT3 AS (
SELECT Locality,Has_Table_booking TABLE_BOOKING
FROM ZOMATO
)
SELECT A.Locality, COUNT(A.TABLE_BOOKING) TABLE_BOOKING_OPTION
FROM CT3 A JOIN CT2 B
ON A.Locality = B.Locality
WHERE A.TABLE_BOOKING = 'YES'
GROUP BY A.Locality;



-- HOW RATING AFFECTS IN MAX LISTED RESTAURANTS WITH AND WITHOUT TABLE BOOKING OPTION (Connaught Place)
SELECT 'WITH_TABLE' TABLE_BOOKING_OPT,COUNT(Has_Table_booking) TOTAL_REST, ROUND(AVG(Rating),2) AVG_RATING
FROM ZOMATO
WHERE Has_Table_booking = 'YES'
AND Locality = 'Connaught Place'
UNION
SELECT 'WITHOUT_TABLE' TABLE_BOOKING_OPT,COUNT(Has_Table_booking) TOTAL_REST, ROUND(AVG(Rating),2) AVG_RATING
FROM ZOMATO
WHERE Has_Table_booking = 'NO'
AND Locality = 'Connaught Place';



-- AVG RATING OF RESTS LOCATION WISE
SELECT COUNTRY_NAME,City,Locality, 
COUNT(RestaurantID) TOTAL_REST ,ROUND(AVG(CAST(Rating AS DECIMAL)),2) AVG_RATING
FROM ZOMATO
GROUP BY COUNTRY_NAME,City,Locality
ORDER BY 4 DESC;



-- FINDING THE BEST RESTAURANTS WITH MODRATE COST FOR TWO IN INDIA HAVING INDIAN CUISINES
SELECT *
FROM ZOMATO
WHERE COUNTRY_NAME = 'INDIA'
AND Has_Table_booking = 'YES'
AND Has_Online_delivery = 'YES'
AND Price_range <= 3
AND Votes > 1000
AND Average_Cost_for_two < 1000
AND Rating > 4
AND Cuisines LIKE '%INDIA%';



-- FIND ALL THE RESTAURANTS THOSE WHO ARE OFFERING TABLE BOOKING OPTIONS WITH PRICE RANGE AND HAS HIGH RATING
SELECT Price_range, COUNT(Has_Table_booking) NO_OF_REST
FROM ZOMATO
WHERE Rating >= 4.5
AND Has_Table_booking = 'YES'
GROUP BY Price_range ;
